### ISSUE TITLE
Meta issue: Better documentation

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GAP.jl#455]
We need to improve the documentation. Some TODOs for that (more can and should be added here)

- [ ] Link up items which are documented but not shown in the manual yet
- [ ] Add description what the package is about
- [ ] Add DFG funding notice to package manual
- [ ] Resolve issue #356
- [ ] Add examples; Resolve issue #303
- [ ] Document more functions

@ThomasBreuer @mohamed-barakat feel free to add more here or suggest them in comments. Also, contributions are welcome ;-)

**Comment by fingolfin** [comment]
Closing this; things have either been resolved, have their own issue, or are too vague to be useful.
